"""Neural surrogate for fast Cmax prediction.

Replaces the full PBPK ODE solve with a single MLP forward pass:
    12D ADME parameters → log10(Cmax)

Trained on synthetic data generated by the JAX engine (Phase 1).
Achieves ~1000x speedup over ODE for MC propagation.

Gate criterion: 95% of predictions within 20% of engine Cmax.
Falls back to full ODE when surrogate uncertainty is high.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING

import numpy as np

logger = logging.getLogger(__name__)

try:
    import jax
    jax.config.update("jax_enable_x64", True)
    import jax.numpy as jnp
    import equinox as eqx
    _HAS_EQX = True
except ImportError:
    _HAS_EQX = False

if TYPE_CHECKING:
    from sisyphus.engine.compiler import CompiledODE, ResolvedParams


# Feature order (must match training exactly):
# [log10(CLint), fup, logP, pKa_or_7, is_neutral, is_acid, is_base,
#  MW/500, log10(dose), log10(Peff), log10(sol), log10(renal_cl)]
FEATURE_NAMES = [
    "log10_clint", "fup", "logp", "pka_or_7",
    "is_neutral", "is_acid", "is_base",
    "mw_scaled", "log10_dose", "log10_peff", "log10_sol", "log10_renal_cl",
]
N_FEATURES = 12


@dataclass
class SurrogateConfig:
    """Configuration for surrogate model."""
    hidden_sizes: tuple[int, ...] = (256, 256, 128)
    model_dir: Path = Path("models/surrogate")
    n_ensemble: int = 5
    accuracy_threshold: float = 0.20   # 20% relative error gate
    coverage_threshold: float = 0.95   # 95% of parameter space


class CmaxSurrogate(eqx.Module if _HAS_EQX else object):
    """Equinox MLP: 12D ADME → log10(Cmax).

    Architecture mirrors Gate 1 (R²=0.9986):
        12 → 256 → 256 → 128 → 1 with ReLU activations.
    """
    layers: list

    def __init__(self, key, hidden_sizes=(256, 256, 128)):
        if not _HAS_EQX:
            raise ImportError("equinox required: pip install equinox")
        sizes = [N_FEATURES] + list(hidden_sizes) + [1]
        keys = jax.random.split(key, len(sizes) - 1)
        self.layers = []
        for i, (k, in_s, out_s) in enumerate(zip(keys, sizes[:-1], sizes[1:])):
            self.layers.append(eqx.nn.Linear(in_s, out_s, key=k))

    def __call__(self, x):
        """Forward pass: (12,) → scalar."""
        for layer in self.layers[:-1]:
            x = jax.nn.relu(layer(x))
        return self.layers[-1](x).squeeze(-1)


def params_to_features_single(params: ResolvedParams) -> np.ndarray:
    """Convert ResolvedParams to 12D feature vector for surrogate.

    Extracts the same features used in Gate 1 training.
    """
    fup = params.drug_param("fup")
    peff = params.drug_param("peff")
    dose = params.drug_param("dose_mg")
    mw = params.drug_mw()
    renal_cl = params.drug_param("renal_clearance")

    # Total CLint from all enzyme nodes
    clint_total = 0.0
    for node_name in params._enzymes:
        ivive = params.node_param(node_name, "ivive_scaling") if node_name in params._ivive_scaling else 0.0
        for tag, abundance in params.node_enzymes(node_name).items():
            affinity = params.drug_enzyme_affinity(tag)
            if affinity > 0 and abundance > 0:
                clint_total += abundance * affinity  # raw CLint (pre-IVIVE)

    # Compound type from Kp pattern (heuristic: base if adipose Kp > 10)
    # Simplified: use drug's compound_type if available
    compound_type = getattr(params._drug, 'compound_type', 'neutral')
    pka = getattr(params._drug, 'pka', None)

    features = np.array([
        np.log10(max(clint_total, 1e-6)),          # log10(CLint)
        fup,                                         # fup
        getattr(params._drug, 'logp', 2.0) if hasattr(params._drug, 'logp') else 2.0,  # logP
        pka if pka is not None else 7.0,             # pKa or 7
        1.0 if compound_type == "neutral" else 0.0,  # is_neutral
        1.0 if compound_type == "acid" else 0.0,     # is_acid
        1.0 if compound_type == "base" else 0.0,     # is_base
        mw / 500.0,                                  # MW/500
        np.log10(max(dose, 1e-6)),                   # log10(dose)
        np.log10(max(peff, 1e-6)),                   # log10(Peff)
        np.log10(max(getattr(params._drug, 'solubility', type('', (), {'mean': 1.0})).mean, 1e-10)),  # log10(sol)
        np.log10(max(renal_cl, 1e-10)),              # log10(renal_cl)
    ], dtype=np.float64)

    return features


def load_surrogate_ensemble(
    model_dir: Path = Path("models/surrogate"),
    n_ensemble: int = 5,
) -> list[CmaxSurrogate]:
    """Load a trained ensemble of surrogate models."""
    if not _HAS_EQX:
        raise ImportError("equinox required: pip install equinox")
    models = []
    for i in range(n_ensemble):
        path = model_dir / f"cmax_mlp_{i}.eqx"
        if not path.exists():
            raise FileNotFoundError(f"Surrogate model not found: {path}")
        template = CmaxSurrogate(jax.random.PRNGKey(0))
        model = eqx.tree_deserialise_leaves(str(path), template)
        models.append(model)
    return models


def predict_surrogate_ensemble(
    models: list[CmaxSurrogate],
    features: np.ndarray,
    scaler_mean: np.ndarray,
    scaler_std: np.ndarray,
) -> tuple[np.ndarray, np.ndarray]:
    """Predict log10(Cmax) with uncertainty from ensemble.

    Args:
        models: List of trained CmaxSurrogate instances.
        features: (N, 12) feature matrix.
        scaler_mean: (12,) feature means for standardization.
        scaler_std: (12,) feature stds for standardization.

    Returns:
        (predictions, uncertainties): each shape (N,).
        Prediction = ensemble mean. Uncertainty = ensemble std.
    """
    X = (features - scaler_mean) / np.maximum(scaler_std, 1e-10)
    X_jax = jnp.array(X)

    all_preds = []
    for model in models:
        pred_fn = jax.vmap(model)
        preds = np.array(pred_fn(X_jax))
        all_preds.append(preds)

    all_preds = np.stack(all_preds, axis=0)  # (n_ensemble, N)
    mean_pred = np.mean(all_preds, axis=0)
    std_pred = np.std(all_preds, axis=0)

    return mean_pred, std_pred


def solve_surrogate_batch(
    models: list[CmaxSurrogate],
    params_list: list[ResolvedParams],
    scaler_mean: np.ndarray,
    scaler_std: np.ndarray,
) -> tuple[np.ndarray, np.ndarray]:
    """Batch surrogate prediction for MC propagation.

    Args:
        models: Trained ensemble.
        params_list: N ResolvedParams (one per MC sample).
        scaler_mean, scaler_std: Feature standardization.

    Returns:
        (cmax_array, uncertainty_array): each shape (N,).
        cmax_array = 10^pred_log10_cmax * dose.
    """
    features = np.stack([params_to_features_single(p) for p in params_list])
    doses = np.array([p.drug_param("dose_mg") for p in params_list])

    pred_log_cd, uncertainty = predict_surrogate_ensemble(
        models, features, scaler_mean, scaler_std,
    )

    # Convert log10(Cmax/dose) → Cmax
    cmax = 10**pred_log_cd * doses

    return cmax, uncertainty


def validate_surrogate(
    models: list[CmaxSurrogate],
    scaler_mean: np.ndarray,
    scaler_std: np.ndarray,
    engine_features: np.ndarray,
    engine_cmax: np.ndarray,
    threshold: float = 0.20,
) -> dict:
    """Validate surrogate accuracy against engine ground truth.

    Returns dict with coverage, max_error, r2, and pass/fail.
    """
    pred_log_cd, _ = predict_surrogate_ensemble(
        models, engine_features, scaler_mean, scaler_std,
    )

    engine_log_cd = np.log10(np.maximum(engine_cmax, 1e-10))
    valid = np.isfinite(pred_log_cd) & np.isfinite(engine_log_cd) & (engine_cmax > 0)
    pred_v = pred_log_cd[valid]
    true_v = engine_log_cd[valid]

    # Fold error
    fold_err = 10**np.abs(pred_v - true_v)
    within_threshold = np.mean(fold_err <= (1 + threshold))
    max_fold = float(np.max(fold_err))

    # R² on log scale
    ss_res = np.sum((pred_v - true_v) ** 2)
    ss_tot = np.sum((true_v - np.mean(true_v)) ** 2)
    r2 = 1 - ss_res / ss_tot if ss_tot > 0 else 0.0

    result = {
        "n_valid": int(np.sum(valid)),
        "coverage_within_20pct": float(within_threshold),
        "max_fold_error": float(max_fold),
        "r2_log_scale": float(r2),
        "gate_pass": bool(within_threshold >= 0.95),
    }

    logger.info(
        "Surrogate validation: coverage=%.1f%% (gate=95%%), R²=%.4f, max_fold=%.2fx",
        within_threshold * 100, r2, max_fold,
    )
    return result
